### Variables
@host = http://localhost:8080
@serviceName = deployko-nginx
@imageRepository = docker.io/library/nginx
@imageVersion = latest

### Create service
POST {{host}}/services
Content-Type: application/json

{
  "name": "{{serviceName}}",
  "imageRepository": "{{imageRepository}}"
}

### Create duplicate service
POST {{host}}/services
Content-Type: application/json

{
  "name": "{{serviceName}}",
  "imageRepository": "{{imageRepository}}"
}

### Create invalid service
POST {{host}}/services
Content-Type: application/json

{
  "name": "Deployko Api",
  "imageRepository": "{{imageRepository}}"
}

### Delete service
DELETE {{host}}/services/{{serviceName}}

### Delete missing service
DELETE {{host}}/services/missing-service

### Delete invalid service
DELETE {{host}}/services/Deployko Api

### Deploy
POST {{host}}/services/{{serviceName}}/runtime/deploy
Content-Type: application/json

{
  "imageVersion": "{{imageVersion}}"
}

### Deploy missing
POST {{host}}/services/missing-service/runtime/deploy
Content-Type: application/json

{
  "imageVersion": "{{imageVersion}}"
}

### Deploy invalid image version
POST {{host}}/services/{{serviceName}}/runtime/deploy
Content-Type: application/json

{
  "imageVersion": "feature/build"
}

### Start
POST {{host}}/services/{{serviceName}}/runtime/start

### Start missing
POST {{host}}/services/missing-service/runtime/start

### Start invalid
POST {{host}}/services/Deployko Api/runtime/start

### Stop
POST {{host}}/services/{{serviceName}}/runtime/stop

### Stop missing
POST {{host}}/services/missing-service/runtime/stop

### Stop invalid
POST {{host}}/services/Deployko Api/runtime/stop
