### Variables
@host = http://localhost:8080
@serviceName = deployko-nginx
@imageRepository = docker.io/library/nginx
@imageVersion = latest
@hostPort = 8080
@hostProtocol = TCP
@containerPort = 80
@containerProtocol = TCP

### Create service
POST {{host}}/services
Content-Type: application/json

{
  "name": "{{serviceName}}",
  "imageRepository": "{{imageRepository}}"
}

### Create duplicate service
POST {{host}}/services
Content-Type: application/json

{
  "name": "{{serviceName}}",
  "imageRepository": "{{imageRepository}}"
}

### Create invalid service
POST {{host}}/services
Content-Type: application/json

{
  "name": "Deployko Api",
  "imageRepository": "{{imageRepository}}"
}

### Delete service
DELETE {{host}}/services/{{serviceName}}

### Delete missing service
DELETE {{host}}/services/missing-service

### Delete invalid service
DELETE {{host}}/services/Deployko Api

### Get port mappings
GET {{host}}/services/{{serviceName}}/runtime-configuration/port-mappings

### Get port mappings missing service
GET {{host}}/services/missing-service/runtime-configuration/port-mappings

### Create port mapping
POST {{host}}/services/{{serviceName}}/runtime-configuration/port-mappings
Content-Type: application/json

{
  "hostPort": {{hostPort}},
  "hostProtocol": "{{hostProtocol}}",
  "containerPort": {{containerPort}},
  "containerProtocol": "{{containerProtocol}}"
}

### Create duplicate port mapping
POST {{host}}/services/{{serviceName}}/runtime-configuration/port-mappings
Content-Type: application/json

{
  "hostPort": {{hostPort}},
  "hostProtocol": "{{hostProtocol}}",
  "containerPort": {{containerPort}},
  "containerProtocol": "{{containerProtocol}}"
}

### Create port mapping missing service
POST {{host}}/services/missing-service/runtime-configuration/port-mappings
Content-Type: application/json

{
  "hostPort": {{hostPort}},
  "hostProtocol": "{{hostProtocol}}",
  "containerPort": {{containerPort}},
  "containerProtocol": "{{containerProtocol}}"
}

### Create invalid port mapping
POST {{host}}/services/{{serviceName}}/runtime-configuration/port-mappings
Content-Type: application/json

{
  "hostPort": 70000,
  "hostProtocol": "{{hostProtocol}}",
  "containerPort": {{containerPort}},
  "containerProtocol": "{{containerProtocol}}"
}

### Delete port mapping
DELETE {{host}}/services/{{serviceName}}/runtime-configuration/port-mappings/{{hostProtocol}}/{{hostPort}}

### Delete port mapping missing service
DELETE {{host}}/services/missing-service/runtime-configuration/port-mappings/{{hostProtocol}}/{{hostPort}}

### Delete missing port mapping
DELETE {{host}}/services/{{serviceName}}/runtime-configuration/port-mappings/{{hostProtocol}}/8081

### Deploy
POST {{host}}/services/{{serviceName}}/runtime/deploy
Content-Type: application/json

{
  "imageVersion": "{{imageVersion}}"
}

### Deploy missing
POST {{host}}/services/missing-service/runtime/deploy
Content-Type: application/json

{
  "imageVersion": "{{imageVersion}}"
}

### Deploy invalid image version
POST {{host}}/services/{{serviceName}}/runtime/deploy
Content-Type: application/json

{
  "imageVersion": "feature/build"
}

### Start
POST {{host}}/services/{{serviceName}}/runtime/start

### Start missing
POST {{host}}/services/missing-service/runtime/start

### Start invalid
POST {{host}}/services/Deployko Api/runtime/start

### Stop
POST {{host}}/services/{{serviceName}}/runtime/stop

### Stop missing
POST {{host}}/services/missing-service/runtime/stop

### Stop invalid
POST {{host}}/services/Deployko Api/runtime/stop
